### ISSUE TITLE
Get linked tables for a record in the same model?

### ISSUE THREAD

**Issue by MeFuMo** [nenad-zivkovic/yii2-advanced-template#10]
Hi.

Not sure if it is ok to ask this here. Please feel free to scold me and point me to the right place, as I'll probably have some stupid questions about the template functionality now that I started to dive into playing with Yii.

I am pretty new in Yii2, I've been looking around and probably I am a bit confused because of how people do things differently.

In the user admin area from the advanced template, I tried to use inline editing from Kartik extensions (I used KartikGii, basically it outputs Gii generated templates and changes the default forms with all those widgets that Kartik guy made, not sure if the enhanced advanced template has any very custom CSS).

So we have "role" in the vanilla "view user" view, and it takes the role dropdown as:

backend/users/_form.php:

```php
<?php foreach (AuthItem::getRoles() as $item_name): ?>
<?php $roles[$item_name->name] = $item_name->name ?>
<?php endforeach ?>
<?php echo $form->field($role, 'item_name')->dropDownList($roles) ?>
```

So the field is taking the dropdown from the $role model using the $roles array to set the form values. When using an inline editing widget, we need to pull all the data from a single model in the widget, or so does the documentation say (so we couldn't even use related things like "role.auth_item" or any "related" field name in the form). 

So something like:

backend/users/view.php (as we use the same view to view and edit)

```php

use kartik\detail\DetailView;

/* @var $model common\models\User */
/* @var $role common\models\Role */

...

DetailView::widget([
		'model' => $model,
		'condensed' => false,
		'hover' => true,
		'mode' => Yii::$app->request->get('edit') == 't' ? DetailView::MODE_EDIT : DetailView::MODE_VIEW,
		'panel' => [
			'heading' => $this->title,
			'type' => DetailView::TYPE_INFO,
		],
               'attributes' => [
			'username',
			'email:email',

                         ...

			 [     // here we go
                             'attribute' => 'item_name',
			     'type' => DetailView::INPUT_SELECT2,
                             'value' => $model->getRoleName()  // The 'view mode' value for the field
				'widgetOptions' => [ // for what i understood, this array will set the "edit mode" widget options
					'data' => $roles, // the whole roles array
					'options' => ['placeholder' => 'Select ...'],
				],
			],
...

```

I tried to point to the $role model in different places (inside the item_name stuff, widgetOptions and so) but it seems to ignore it. When editing, the item_name field is plainly deselected and not saving the value (basically the same as if i call the dropdown with the user $model instead of the $role). So i think there's something missing that prevents me from getting the whole model at once.

Is there any way to actually pack all the linked data in the same model and get it from there instead of using both user and role? As role is indeed a link table alias for the auth_assignment table, shouldn't it be taken by the user model by itself with something like getRole() method set in the Users Model file? Wasn't that the magic of Yii? :P

Sorry about the long stuff and please, keep up the good work. I'll be delighted to contribute to your template (once i find my way around, as I am just starting ;) ).

**Comment by nenad-zivkovic** [comment]
Sorry but I do not understand this code, you will have to ask Kartik. I do not use his widgets except the modified password strength that I included in template. I do not even understand what you want to do ? What is your goal here ? You want to display roles or something ?

**Comment by MeFuMo** [comment]
Sorry, I'll leave Kartik's widgets out of this :P

I mainly want to know if it is possible to have the whole user model (with all related fields, including the auth_assignment linked field) in $user, so I do not need to pass both $role and $user to the template and it updates all user related models from itself. 

Practically, the role dropdown would be:

```php
<?php foreach (AuthItem::getRoles() as $item_name): ?>
<?php $roles[$item_name->name] = $item_name->name ?>
<?php endforeach ?>
// here comes the change
<?php echo $form->field($user, 'item_name')->dropDownList($roles) ?>
```
Please note I am changing in the dropdown call the $role model for the $user model. Sorry if I confuse you, as I told you I am pretty new :)

**Comment by nenad-zivkovic** [comment]
If you do not have role object, how your are going to save role ? As far as I know, user object can not save Role object attributes. If you look at ```UserController actionCreate```, you will see that we need to instantiate Role model to be able to save item_name. If you are asking, can you save related model fields without having to instantiate Role class, I think that you can not, but you have to ask Yii2 developers, not me. Good luck :-)

**Comment by MeFuMo** [comment]
I was actually hoping something like this could be done, applied to users (example from Yii2 documentation):

public function getItems()
{
    return $this->hasMany(Item::className(), ['id' => 'item_id'])
                ->viaTable('order_item', ['order_id' => 'id']);
}

Anyway I'll try my luck in the Yii2 forums, as I have some silly questions on my mind. Thanks for your time, and for this Enhanced template :)
