### ISSUE TITLE
Use yii2-admin with yii2-advanced-template

### ISSUE THREAD

**Issue by thassan** [nenad-zivkovic/yii2-advanced-template#11]
I followed the tutorial on: http://www.freetuts.org/tutorial/view?id=6
All works well.
Then I tried to install https://github.com/mdmsoft/yii2-admin exactly how I installed it before on the standard yii2 advanced app template, per instructions:
http://mdmsoft.github.io/yii2-admin/index.html
http://www.mohantabdar.com.np/rbac-manager-for-yii-2-yii2-admin/
I only skipped the rbac migrate command since the instructions of installing yii2-advanced-template already creates the rbac tables and inserts roles, permissions, rule etc.
Now, I am able to access http://localhost/backend/admin instead of http://backend/index.php?r=admin but the pages are not displayed properly as if CSS styles are missing.
Tried changing theme to default to see if it makes any difference but to no avail.
Could you please guide me in the right direction to get the yii2-admin working properly with yii2-advanced-template just like it works on the standard advanced template?
thanks

**Comment by thassan** [comment]
OK I found the reason for the issue.. Bootstrap css files are not loaded. This is because of the following default configuration in _protected/common/config/main.php
```php
    'components' => [
        'assetManager' => [
            'bundles' => [
                // we will use bootstrap css from our theme
//                'yii\bootstrap\BootstrapAsset' => [
//                    'css' => [], // do not use yii default one
//                ],
            ...
            ],
        ],
        ....
```
commenting those 3 lines out solves the issue, but messes up the theme on the rest of the pages.

How to integrate nicely?

**Comment by thassan** [comment]
I found a workaround, but I'm sure there are better ways to get this done.

in: _protected/vendor/mdmsoft/yii2-admin/views/layouts/main.php

after:
```
        <?php $this->head() ?>
```
I added the following 2 lines:

```
        <?php list(, $url) = Yii::$app->assetManager->publish('@webroot/themes/cerulean'); ?>
        <?php $this->registerCssFile($url.'/css/bootstrap.min.css'); ?>
```

Can you suggest any better option?

**Comment by nenad-zivkovic** [comment]
These templates are using a little bit different html structure and css comparing to default templates. This is why you need to customize your css ( yii2-admin or your custom ones ) to fit nicely with templates. If I were you I would take yii2-admin css, and make theme from it, similar to default ones that exists in template. So I would examine css coming with yii2-admin and one coming from any theme that you like. Then I would create my own theme, like "admin", that will fit with my project.
