### ISSUE TITLE
Rbac init error

### ISSUE THREAD

**Issue by timohus** [nenad-zivkovic/yii2-advanced-template#17]
When doing "yii rbac/init" an error appears: PHP Compile Error 'yii\base\ErrorException' with message 'Declaration of common\rbac\rules\AuthorRule::execute() must be compatible with yii\rbac\Rule::execute($item, $params)'
Had to edit _protected\vendor\yiisoft\yii2\rbac\Rule.php. I've changed this "abstract public function execute($item, $params);" to this "abstract public function execute($user, $item, $params);"

**Comment by nenad-zivkovic** [comment]
There was some silly mistake in my migration, I've fixed it in 2.2.1. But other than that rbac/init should work without hacking framework. Have you installed rbac tables by running migration ./yii migrate ? You have done all the steps of the installation process described in the guide ?

**Comment by timohus** [comment]
Sorry, my bad. I missed one important step. I've done a fresh installation of composer before and I've missed to do this: < composer global require "fxp/composer-asset-plugin:~1.0.0" >
Now I've done it all from the beginning (after installing composer asset plugin) and everything works great. Thank you!

**Comment by nenad-zivkovic** [comment]
No problem
