### ISSUE TITLE
In Sign Up page, I got error Class 'nenad\passwordStrength\StrengthValidator' not found

### ISSUE THREAD

**Issue by kianhuat** [nenad-zivkovic/yii2-advanced-template#18]
Hi Nenad,

When I click on Sign Up page, it show error:

<img width="825" alt="screen shot 2015-08-10 at 10 17 18 pm" src="https://cloud.githubusercontent.com/assets/2578348/9173617/e217f74e-3fad-11e5-9764-b96de793d167.png">

I already put in nenad/yii2-password-strength in vendor folder. But, system still can't find that class...

<img width="1034" alt="screen shot 2015-08-10 at 10 17 58 pm" src="https://cloud.githubusercontent.com/assets/2578348/9173653/17956186-3fae-11e5-88c9-7d58429bbe61.png">

How to fix this?

Thanks.

**Comment by nenad-zivkovic** [comment]
You need to install tempaltes using Composer. I do not support other kinds of installations. You can find my tutorial here : `http://www.freetuts.org/tutorial/view?id=6`

**Comment by kianhuat** [comment]
Thanks.
