### ISSUE TITLE
Installing Admin LTE theme

### ISSUE THREAD

**Issue by p4prawin** [nenad-zivkovic/yii2-advanced-template#20]
I have installed this template and trying to install Admin LTE theme (https://github.com/dmstr/yii2-adminlte-asset).
i have installed the theme using composer as suggested in their documentation.

but i could not figure out how to set up configuration.

please help...
Thank You

**Comment by nenad-zivkovic** [comment]
Sorry, but installation of third party software is not related with template but with third party software. I dont use that theme so I do not know, and can not do this job for you. I hope you will figure it out. Good luc.
