### ISSUE TITLE
Migration class name error

### ISSUE THREAD

**Issue by flarpy** [nenad-zivkovic/yii2-advanced-template#21]
Downloaded template today, ran migration, got:

Class 'm141022_115912_create_rbac_tables' not found'

In console/migrations/m141022_115912_create_rbac_tables.php
class m1401022_115912_create_rbac_tables extends \yii\db\Migration
should be
class m141022_115912_create_rbac_tables extends \yii\db\Migration

Thanks

**Comment by nenad-zivkovic** [comment]
What version you have tried to install ? You shouldn't have this problem. I just tried full installation and everything is ok. 

You can download the latest version with this command: 
`composer create-project nenad/yii2-advanced-template advanced`

**Comment by flarpy** [comment]
Hi

I forked from github this morning.

On 28 September 2015 at 16:59, Nenad Zivkovic <notifications@github.com>
wrote:

> What version you have tried to install ? You shouldn't have this problem.
> I just tried full installation and everything is ok.
>
> You can download the latest version with this command:
> composer create-project nenad/yii2-advanced-template advanced
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nenad-zivkovic/yii2-advanced-template/issues/21#issuecomment-143787953>
> .
>



-- 
Peter Dunham

**Comment by nenad-zivkovic** [comment]
Composer installation should work : `http://www.freetuts.org/tutorial/view?id=6#advanced`

**Comment by nenad-zivkovic** [comment]
It must work nicely in 2.2.3 version
