### ISSUE TITLE
./yii migrate No such file or directory vendor/autoload.php

### ISSUE THREAD

**Issue by Kanasagra-Jaydip** [nenad-zivkovic/yii2-advanced-template#22]
When i use ./yii migrate command on terminal, then show me an bellow error.

PHP Warning:  require(/var/www/html/advanced/_protected/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/advanced/_protected/yii on line 16

I am using version of yii -> composer create-project nenad/yii2-advanced-template advanced

Please tell me how to solve this.
Thanks,

**Comment by nenad-zivkovic** [comment]
You have to install templates using Composer. This is how you install Yii2 default templates using Composer on Ubuntu: http://www.freetuts.org/tutorial/view?id=4

After you learn how to install default templates, you can learn how to install improved here : http://www.freetuts.org/tutorial/view?id=6
