### ISSUE TITLE
requirements.php path error

### ISSUE THREAD

**Issue by sganz** [nenad-zivkovic/yii2-advanced-template#23]
Not sure if the path is set up correctly in the requirements.php. When I tried to run it, it complains about - 

```The path to yii framework seems to be incorrect.```

I added a slash to the requirements.php file as below and it seemed to work. This applies to both the basic and advanced-template. 

```php
// you may need to adjust this path to the correct Yii framework path
$frameworkPath = dirname(__FILE__) . '/_protected/vendor/yiisoft/yii2';
```
Only a minor issue at best.

Thanks

Sandy

**Comment by nenad-zivkovic** [comment]
Thank you. I haven't tried to run that, like ever... :)
I'm going to fix it soon.

**Comment by sganz** [comment]
Ha, yeah, I had a configuration problem so I decided to run it and found the problem. I doubt many do run it at all once do you set up an environment once. 

Sandy
