### ISSUE TITLE
Would it be possible to use this template with AngularJS?

### ISSUE THREAD

**Issue by con322** [nenad-zivkovic/yii2-advanced-template#27]
Any advice/tops for creating a one page application? 

I have found this guide but its using the default application.

https://www.gitbook.com/book/hscstudio/angular1-yii2/details

**Comment by rodzadra** [comment]
Hi, try this video

https://t.co/A5QNRyecyn

**Comment by nenad-zivkovic** [comment]
I dont see reason why not. Its a matter of your configuration.
