### ISSUE TITLE
installling and composer update issue

### ISSUE THREAD

**Issue by ajayphp** [nenad-zivkovic/yii2-advanced-template#28]
Hi,

I tried with your yii2 template, and did as you mention in readme

after create project and yii migrate etc, vendor folder was blank
and when i did composer update 
then following error:

===========
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2 2.0.7 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.6 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.5 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.4 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.3 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.2 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.1 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.0 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - Removal request for yiisoft/yii2 == 2.0.0.0-beta
    - Installation request for yiisoft/yii2 * -> satisfiable by yiisoft/yii2[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.0-beta].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

============

i tried with tweak in composer stable to dev, and update
still following error:

============
Package yiisoft/jquery is abandoned, you should avoid using it. No replacement was suggested.
Package yiisoft/jquery-pjax is abandoned, you should avoid using it. Use install via bower instead instead.

=========

how signup page link broken on site. 

Please tell me what might be i am missing and how to correct these issue
and will that update to latest yii2 

Regards

**Comment by nenad-zivkovic** [comment]
Have you isntalled ? : 
`composer global require "fxp/composer-asset-plugin:~1.1.1"`
