### ISSUE TITLE
Fresh install problems

### ISSUE THREAD

**Issue by MaartAl** [nenad-zivkovic/yii2-advanced-template#4]
After following the installation steps, 
"You are done, you can start your application in your browser:"
i get:
Unknown Method – yii\base\UnknownMethodException
Calling unknown method: yii\web\UrlManager::addRules()

Can someone help me with this?

**Comment by nenad-zivkovic** [comment]
have you fixed it ?

**Comment by MaartAl** [comment]
Dear Nenad,

Thanks for your kind support.

I dit a total re-install, seemed there was something wrong with composer. (had to self-update and set somekind of github key).
It then installed correctly but after that:
When i signed up the first user it gave me an error, so the first user was not the super-user but just regular admin i think. (Status 10?).

Then i trew it all away again : S, been looking in to Yii for 2 weeks now and i’am trying to figureing out what the best solution for me is. Maby you can help me a bit.
I’ve setup an ‘basic- installation’ and got that one working like i wanted (kinda), but i needed a user-profile page where users can built their own ‘profile’ and the admin manages theyr profile information.

I think i need a frondend / backend setup but maby i can work it out with the basic setup + amnah/yii2-user.

Hmmm i feel like a n00b 

Cheers!
Maarten

**Comment by nenad-zivkovic** [comment]
Status 10 means that it is active. First user should be theCreator ( super Admin ), and all others should be members. Maybe you haven't installed rbac authorization data.

You can follow this tutorial, it may help you:

http://freetuts.org/tutorial/view?id=6

Good luck

**Comment by MaartAl** [comment]
Cheers, 
I give it another try tomorrow ;)
