### ISSUE TITLE
Unable to resolve the request: site/request-password-reset in backend

### ISSUE THREAD

**Issue by uran1980** [nenad-zivkovic/yii2-advanced-template#6]
When I try to reset password in backend ```/backend/site/login```
![2015-01-08-15-20-01](https://cloud.githubusercontent.com/assets/1616795/5663049/485c53cc-974a-11e4-957a-c5c2ec8249b5.png)

This error occured:
![2015-01-08-15-20-02](https://cloud.githubusercontent.com/assets/1616795/5663058/62a5e34c-974a-11e4-818d-86f6aef890ff.png)

**Comment by nenad-zivkovic** [comment]
Password is meant to be reset through frontend. I forgot to remove that link. I will fix it in a sec.

**Comment by nenad-zivkovic** [comment]
Version 2.1.1 fix it. Thanks for report :D
