### ISSUE TITLE
Get article category name within view to use as title

### ISSUE THREAD

**Issue by con322** [nenad-zivkovic/yii2-advanced-template#7]
So I have the following code which displays articles within the id of the parameter.

Controller
```
     public function actionCategory($id)
    {

        $model = new Article();

        $searchModel = new ArticleSearch();

        $query = Article::find()
        ->where(['category' => $id]);

         $dataProvider = new ActiveDataProvider([
                        'query' => $query,
                        ]);

        return $this->render('category', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'model'=>$model,
        ]);
    }
```

So localhost:8888/advanced/article/category?id=1 will display all articles with the category id of 1

In my view if I use the following code it only displays 'sport' as I dont know how to pass the id to the model function.

View
```
<?= $model->CategoryName ?>
```

Model funtion
```
    public function getCategoryName($category = null)
    {
        $category = (empty($category)) ? $this->category : $category ;

        if ($category === self::CATEGORY_ECONOMY)
        {
            return Yii::t('app', 'Economy');
        }
        elseif ($category === self::CATEGORY_SOCIETY)
        {
            return Yii::t('app', 'Society');
        }
        else
        {
            return Yii::t('app', 'Sport');
        }
    }
```

**Comment by con322** [comment]
When using <?= $model->CategoryName ?> in view it displays the name that the article is in however when using it in my category view no id is being passed to the model function get category name. How do I pass the id parameter/current category id to the function.

Is my code so far correct in terms of setting up a category view?

**Comment by nenad-zivkovic** [comment]
Are you using some widget like Gridview from presentation ?

You can try something like this: ```<?= $model->getCategoryName($id) ?>``` but if you are still unsure what to do, please post me your view code.

**Comment by con322** [comment]
Thanks for replying, I was using 

   $this->title = $model->getCategoryName;

In order to use the current category name as page title, so some how I need to pass the $id to the getCategoryName function either in my category function within my controller and then display it in view or in my view do something like you have suggested however i get the following error message:

    Getting unknown property: yii\web\View::id

**Comment by nenad-zivkovic** [comment]
Try this: ```$this->title = $model->getCategoryName($model->id);```
